### ISSUE TITLE
Please for to be creating map to meeting place

### ISSUE THREAD

**Issue by SquadronROE** [willia4/bookclub#35]
Either embed a map to the meeting place or make the meeting place a clickable link that allows us to see where to go.

**Comment by willia4** [comment]
Since the meeting place is usually "**[REDACTED]**'s House", I'm not sure how eager they would be to have their address on a web page protected only by my potentially-buggy implementation of Facebook auth. 

I also like the idea that it's just a loose text field so you can type things like "The Dude's House" or "The Bowling Alley" without having to enter in a correctly-formatted address. 

If **[REDACTED]** is okay with that idea, though, it wouldn't be terribly difficult to implement.

**Comment by SquadronROE** [comment]
It's very low priority considering how infrequently new meeting places are
brought up and new people are added to the group. I just thought of it and
wanted to toss it onto the backlog.

**Comment by willia4** [comment]
Yes. I had thought of putting a map there just to fill space but couldn't figure out how to do it without being creepy.

**Comment by SquadronROE** [comment]
Just put a picture of your face in there to fill space.

**Comment by willia4** [comment]
Triaged: Will Not Address
